channels:
  - conda-forge
  - usgs-astrogeology
  - anaconda
  - defaults
dependencies:
   - click
   - requests
   - geopandas
   - pvl
   - sqlalchemy
   - geoalchemy2
   - pywget
   - plio
   - requests-futures
