# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/bayleef

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "environment.yml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
            bash miniconda.sh -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            hash -r
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda info -a
            conda env create --file environment.yml -n bayleef
            source activate bayleef
            conda install pytest
            conda install mock
            pytest .

      - save_cache:
          paths:
            - ./bayleef
          key: v1-dependencies-{{ checksum "environment.yml" }}

      - store_artifacts:
          path: test-reports
          destination: test-reports
