package:
  name: bayleef
  version: 0.2.2

channels:
  - conda-forge
  - menpo
  - usgs-astrogeology

source:
   path: ..

requirements:
  build:
   - mock
   - pytest
   - click
   - requests
   - geopandas
   - pvl
   - sqlalchemy
   - geoalchemy2
   - pywget
   - plio
   - requests-futures

  run:
   - mock
   - pytest
   - click
   - requests
   - geopandas
   - pvl
   - sqlalchemy
   - geoalchemy2
   - pywget
   - plio
   - requests-futures
