package:
  name: bayleef
  version: 0.2.1

channels:
  - conda-forge
  - menpo
  - usgs-astrogeology

source:
   git_url: https://github.com/USGS-Astrogeology/bayleef.git

requirements:
  build:
   - mock
   - pytest
   - click
   - requests
   - geopandas
   - pvl

  run:
   - mock
   - pytest
   - click
   - requests
   - geopandas
   - pvl
